### ISSUE TITLE
Touching a menu item selects it

### ISSUE THREAD

**Issue by fubar-coder** [Odonno/modern-gitter-winjs#17]
When I open the hamburger menu and touch "Rooms", it always gets selected. Please make all texts not-selectable.

**Comment by Odonno** [comment]
Ok, seems like https://github.com/Odonno/modern-gitter-winjs/issues/5

**Comment by Odonno** [comment]
Here is a potential fix : http://stackoverflow.com/questions/6900124/how-to-make-certain-text-not-selectable-with-css

**Comment by Odonno** [comment]
@fubar-coder It is now fixed.
