### ISSUE TITLE
Application always goes to the About screen on load

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#18]
I totally get the idea of having the About screen, however, I don't think this should be the default screen that the application goes to on each load of the application.

Instead, I think the list of rooms should be the default screen that is opened, after the first time the application runs.

This issue was seen on my Nokia Lumia 950 XL, with version 2.2.28 of the application.

**Comment by Odonno** [comment]
About loading after the first time, referred to https://github.com/Odonno/modern-gitter-winjs/issues/6

And currently, the tap on nofitication is not handle, but soon, when you tap one, you'll go directly into the room, yes.

**Comment by Odonno** [comment]
Since you've created #22, we will refer this one to #6.
