### ISSUE TITLE
Unread message count icon is always shown

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#19]
When looking at the Rooms screen, I always see an unread message count icon, even though these say 0 unread messages.

I think the unread message icon should only be shown when the unread message count is greater than 0 for any given room.

This issue was seen on my Nokia Lumia 950 XL, with version 2.2.28 of the application.

**Comment by gep13** [comment]
This is what I am seeing in the Rooms screen:

![image](https://cloud.githubusercontent.com/assets/1271146/12164756/071e577c-b510-11e5-995c-94da6d04e3e0.png)

**Comment by Odonno** [comment]
Yeah, it could be more readible !
