### ISSUE TITLE
Problem viewing messages within room

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#20]
With the latest release of the UWP application, I am seeing an issue viewing the messages within a room.

For example, when going into the Odonno/Modern-Gitter chat room, I see a completely blank screen.  If I scroll up and down, the messages sometimes appear, but then the screen goes blank again.  Other times, the messages stay in place, but then the messages jump to the last message in the room.

This issue was seen on my Nokia Lumia 950 XL, with version 2.2.28 of the application.

**Comment by gep13** [comment]
This is what I am seeing when I open the Modern-Gitter Room:

![image](https://cloud.githubusercontent.com/assets/1271146/12164745/ebb4b260-b50f-11e5-8555-41e4f7981a50.png)

**Comment by Odonno** [comment]
Indeed, the WinJS list-view control is not so easy to use when it comes for messages.

About the white screen, it is due to the refresh of the UI controls which is programmatically random (ex : if it takes time to load messages from network, so the UI will not refresh cause it's too late).

**Comment by gep13** [comment]
> @Odonno said...
> About the white screen, it is due to the refresh of the UI controls which is programmatically random (ex : if it takes time to load messages from network, so the UI will not refresh cause it's too late).

In which case, I think we need some sort of progress indicator to show that "something" is happening.

**Comment by Odonno** [comment]
Yep, but the most important is that then it will never refresh UI... until you may update the UI yourself (ex : resizing screen).

**Comment by gep13** [comment]
Hmm, not sure I fully understand what you are referring to.

**Comment by Odonno** [comment]
There is something like a timeout. After a certain time, it will never refresh UI, so you'll never see messages, but they are clearly loaded, just not visible until UI refresh.
