### ISSUE TITLE
Hamburger menu should disappear when you click on an option

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#21]
Steps to reproduce:
1. Open the Modern Gitter Application
2. Click the hamburger menu
3. Click Rooms

At this point, the hamburger menu that popped out should disappear and show me the chosen selection, i.e. the rooms screen.

Instead, the hamburger menu remains in place, and you have to click to the right of the menu in order to see the rooms, which is not ideal.

This issue was seen on my Nokia Lumia 950 XL, with version 2.2.28 of the application.

**Comment by Odonno** [comment]
I will check. 
I think it works like on desktop (when you click outside the splitview, it close the menu).
I do not own a W10M at the moment.

**Comment by gep13** [comment]
You should be able to use the emulator to do some testing though, right?

**Comment by Odonno** [comment]
It does not work for me...

**Comment by gep13** [comment]
> @Odonno said...
> It does not work for me...

You mean the emulator?

**Comment by Odonno** [comment]
Yes. It runs correctly but the app does not seem to work. I don't know why.

**Comment by gep13** [comment]
@Odonno in version 2.2.53 of the application, this problem seems to have come back again :-(

**Comment by Odonno** [comment]
Yep, that's normal.

**Comment by gep13** [comment]
@Odonno sorry, what do you mean that's normal?  I would expect that the hamburger menu should disappear when I click on say "Rooms" but it stays open.

**Comment by Odonno** [comment]
I mean because of the last version, it does not work. Last version is not stable anymore (if it was before ^^). But, it's clearly a bug. I fix it asap.

**Comment by gep13** [comment]
@Odonno ah, I see, makes sense.  Would it make sense to re-open this issue, or should I raise a new one?

**Comment by Odonno** [comment]
Hi @gep13, 

I tried some Windows 10 apps lately and I see more clearly the behavior of the SplitView. Indeed, there is still a bug because : 
- [x] In desktop mode, actionning a button should not close the SplitView (default behavior)
- [x] In mobile, actionning should fade out the SplitView

**Comment by xperiandri** [comment]
Same issue

**Comment by Odonno** [comment]
It is now fixed in the latest version.
