### ISSUE TITLE
"undefined" in notification messages

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#24]
Not sure what this is, but I think there is something not quite right here:

![image](https://cloud.githubusercontent.com/assets/1271146/12164952/8e5877bc-b511-11e5-9b8a-9d03c50ca801.png)

This issue was seen on my Nokia Lumia 950 XL, with version 2.2.28 of the application.

**Comment by Odonno** [comment]
Yep, Faye Gitter API send events but I do not have time to check at these events. The ones I've seen are : 
- creation of a new message
- edition of a current message
- deletion of a current message

But I suppose there is other events that are not related to messages, and so there is an `undefined` message content
