### ISSUE TITLE
Going into a room with unread messages doesn't decrease the unread count

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#26]
Steps to reproduce:
1. Open the application
2. Find a room that has unread messages
3. Open the room
4. Read the messages
5. Return to room list, message count is still the same
6. Check same room on gitter.im, message count is still the same

**Comment by Odonno** [comment]
You referred to #9 

I close this issue but I take the issue name, that's a better one.

**Comment by Odonno** [comment]
Sorry, I didn't read entirely, it's indeed another bug. But it's linked to #9.

**Comment by gep13** [comment]
Ah, ok, sorry, I did read through the existing issues to see if this was already reported, but I thought #9 was referring to something else :smile:
