### ISSUE TITLE
Back Button on Windows Phone 10 not working as expected

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#40]
Steps to reproduce
1. Click on Rooms
2. Select a Room
3. Click Back
4. Expectation is that the Rooms list will be shown
5. Actual result is that nothing happens
6. Click Back again
7. Application exits

**Comment by Odonno** [comment]
Already fixed, coming in a next version.

**Comment by gep13** [comment]
I have just installed the latest version, and this does indeed seem to be fixed :+1:
