### ISSUE TITLE
Application Crash when no internet connection

### ISSUE THREAD

**Issue by gep13** [Odonno/modern-gitter-winjs#42]
**Steps to reproduce**
- Put phone into flight mode (to simulate no network)
- Start application

**Expected Result**
Application should start normally with stored messages available to browse

**Actual Result**
Application crashses

**Application Version**
2.2.53

**Comment by Odonno** [comment]
Seems fair. I'll check why.

**Comment by Odonno** [comment]
Fixed in 2.3.6

Currently, chat rooms or messages are not locally stored. Maybe in the future.
