### ISSUE TITLE
How to Sign Out?

### ISSUE THREAD

**Issue by xperiandri** [Odonno/modern-gitter-winjs#45]

**Comment by Odonno** [comment]
Obviously, you can't. But that's a feature that will be delivered asap. Just need some few things to get it done :  
- [x] An authentication page (default page when logout)
- [x] Add ability to login later (instead of at the start of the app)
- [x] Handle event when login/logout

**Comment by Odonno** [comment]
Done in 2.3.6

**Comment by xperiandri** [comment]
Cool
I do need to update from Store, don't I?

**Comment by xperiandri** [comment]
I only have 2.2.53 downloaded from store

**Comment by Odonno** [comment]
It will be available soon.
